// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB09VtRHuir4AqDHQgeiRb_fymH0dPG4tk',
    appId: '1:91471994732:web:ff6d27668380c225675d49',
    messagingSenderId: '91471994732',
    projectId: 'chamitosapp',
    authDomain: 'chamitosapp.firebaseapp.com',
    databaseURL: 'https://chamitosapp-default-rtdb.firebaseio.com',
    storageBucket: 'chamitosapp.appspot.com',
    measurementId: 'G-EP5255410C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJcLb1VYgFX0lsVly3FhjWQw9Biwx8qUY',
    appId: '1:91471994732:android:01a03e3c94435b97675d49',
    messagingSenderId: '91471994732',
    projectId: 'chamitosapp',
    databaseURL: 'https://chamitosapp-default-rtdb.firebaseio.com',
    storageBucket: 'chamitosapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPS-EgZM7y5GjobuMX0WvUHUr3JMbA9Vs',
    appId: '1:91471994732:ios:b78b58b1ce969f5a675d49',
    messagingSenderId: '91471994732',
    projectId: 'chamitosapp',
    databaseURL: 'https://chamitosapp-default-rtdb.firebaseio.com',
    storageBucket: 'chamitosapp.appspot.com',
    iosClientId: '91471994732-hlaj4v0ah2dio4lk9l4e7b61qkijckbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chamitosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPS-EgZM7y5GjobuMX0WvUHUr3JMbA9Vs',
    appId: '1:91471994732:ios:b78b58b1ce969f5a675d49',
    messagingSenderId: '91471994732',
    projectId: 'chamitosapp',
    databaseURL: 'https://chamitosapp-default-rtdb.firebaseio.com',
    storageBucket: 'chamitosapp.appspot.com',
    iosClientId: '91471994732-hlaj4v0ah2dio4lk9l4e7b61qkijckbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chamitosapp',
  );
}
